### ISSUE TITLE
Show last 14 days of Reproduction Number data in dashboard graph

### ISSUE THREAD

**Issue by JeroenvdV** [minvws/nl-covid19-data-dashboard#1932] opened 2021-02-16 08:13 UTC
### Describe the bug, issue or concern

The latest Reproduction Number value on https://coronadashboard.rijksoverheid.nl/landelijk/reproductiegetal is currently 0.91 from 22-01-2021. There is more recent data in the linked json data file at https://data.rivm.nl/covid-19/COVID-19_reproductiegetal.json, which has daily values up to 2021-02-05. However, the `Rt_avg` value is not included for the last 14 days. The dashboard seems to (only) display that number. The time of writing is 16-02-2021 and the latest data point shown is 22-01-2021, which means 11 days are not available from RIVM and an _additional_ 14 days are not visualized in the dashboard.

### Problem: Two weeks of data miss because only `Rt_avg` is shown.

'Freshness' of data is quite valuable for dashboard readers. If the purpose of the dashboard is to give insights into the _current_ state of the virus, then missing 14 more days of data greatly affects its value. The largest time gap can be filled in by showing the data available in the `Rt_low` and/or `Rt_up` values, or computing a substitute value for `Rt_avg` in the last 14 days of data. 

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/reproductiegetal
2. Click on "Download data: RIVM"
3. Scroll down to the last data objects in the json array
4. See that there is more recent data than displayed on the page in (1)

### Expected behavior
The data graphed should include the most recent available data points

### Screenshots

![image](https://user-images.githubusercontent.com/5629916/108035544-5cf4ee80-7037-11eb-99fc-256df0f785d5.png)

![image](https://user-images.githubusercontent.com/5629916/108035587-69794700-7037-11eb-8bdf-1c967b6e154e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

### Additional concern: potentially misleading 'latest data' statement

The dashboard page states "Laatste waardes verkregen op dinsdag 9 februari. Wordt wekelijks bijgewerkt." This seems to imply at a glance that the value shown (0.91 from 22-01-2021) represents the state of the virus at a time at most 1 week ago, though in reality it is almost 4 weeks 'old'. 

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment] 2021-02-25 15:50
Thanks for taking the time to write us. We have actually shown the distribution between the upper and lower bound for quite some time. Feedback from visitors caused us to reconsider. It's a challenge to properly explain why the lower/upper bound exists but not the average. Users often did not understand or it was seen as a bug. 

Additionally there is the whole "confidence interval" of 0.95 in this graph. Users often interpreted the estimation band as absolute certainty the R would be between those two bounds. If the eventual R when calculated would be outside those bounds this would also cause confusion, while the simple explanation is that you have better data in hindsight (when establishing the final numbers) than when predicting the value. I hope that makes sense. 

Here's some more explanation on this metric from https://coronadashboard.government.nl/verantwoording#reproduction-number 

> Estimates of R using data from less than 14 days ago could provide an indication of what the definitive value may be, but are not reliable predictors. Estimates using more recent data are less reliable because the data is not yet complete. It is, for instance, impossible to know how many newly confirmed cases will result in hospital admissions in the days ahead.
> 
> Until 11 June 2020 R was calculated on the basis of COVID-19 hospital admissions as large-scale testing was not yet underway. Until 2 November 2020, the graph showing the progression of R over time did not give a value of R for the most recent two weeks but did give a projection of this value in the form of a bandwidth. As of 3 November, the dashboard graph no longer displays this bandwidth.

So, to cut a long story short, this was a choice we made to reduce the comprehension complexity for the average end user. As such I'm closing this ticket.

P.s. The "last value" copy is a topic of ongoing debate. It's true what it states and it's also true that the phrasing might be confusing to some users. Since the message is truthful we'll leave it as is until we find a better solution.

**Closed by VWSCoronaDashboard** 2021-02-25 15:50 UTC
