### ISSUE TITLE
Don't display last two weeks of reproduction number and infectious people; they're inaccurate (underestimated)

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#492] opened 2020-09-30 08:04 UTC
The last two weeks of the reproduction number and at least the last week of the number of infectious people are hugely underestimated in the RIVM data. This misleads the public that things are going better, which is extremely dangerous.

**Problem**
The estimates of the reproduction number and infectious people are structurally too low.

On September 18th, the reproduction number for 11 September was estimated between 0.95 and 1.09. On September 25th, R was estimated at 1.27 (between 1.22 and 1.32), not even close to the previous confidence interval.

<img width="599" alt="Screenshot_235" src="https://user-images.githubusercontent.com/15776622/94657868-5cff8680-0302-11eb-80de-e84315389609.png">
<img width="596" alt="Screenshot_234" src="https://user-images.githubusercontent.com/15776622/94657865-5c66f000-0302-11eb-82bb-eeb5bebab8b4.png">

The same problem persisted last week:
<img width="600" alt="Screenshot_223" src="https://user-images.githubusercontent.com/15776622/94657918-6ee12980-0302-11eb-92a0-f9258f945998.png">
<img width="600" alt="Screenshot_224" src="https://user-images.githubusercontent.com/15776622/94657920-6f79c000-0302-11eb-8938-9e0fc419b643.png">

Infectious people has the same problem 104 thousand people reported for September 18th on 22 September, and 145 thousand reported on September 29th for the same date:
<img width="700" alt="Screenshot_230" src="https://user-images.githubusercontent.com/15776622/94658559-3d1c9280-0303-11eb-9bc3-0da811301ff8.png">
<img width="699" alt="Screenshot_229" src="https://user-images.githubusercontent.com/15776622/94658556-3c83fc00-0303-11eb-8bd6-51cf01ec5176.png">

You can use the Wayback Machine to compare for yourself: 

- https://web.archive.org/web/*/https://coronadashboard.rijksoverheid.nl/landelijk/besmettelijke-mensen
- https://web.archive.org/web/*/https://coronadashboard.rijksoverheid.nl/landelijk/reproductiegetal

**Suggested actions**
- [ ] Immediately stop displaying both the last two weeks of the repoduction number, and the last week of the number of infectious people
- [ ] Upstream this issue to the RIVM, and ask if they can improve their predictions and confidence interval. If that's not possible, stop publishing this inaccurate data.

This issue succeeds #410 (in which the same issue was reported and was closed without action). Please consider prioritizing this, since inaccurate data hugely misleads the public, which can cause dangerous behavior and undermines trust in the government, the OMT and the RIVM.

**Comment by galavanto** [comment] 2020-09-30 08:36
It seems that the stated issue is a problem with unreliable data and the display of this data.

I don't find any problem with the visualization of the unreliable data regarding the reproduction number, as the descriptor for the blue line + the grey shade is very easy to understand and states that the data has a delay of 2 weeks due to it being an calculation. 

The visualization of the calculation of infected people is stated to suffer from the same problem. Since it is an calculation from the RIVM, it has a delay and only shows the actual calculation from the RIVM + an margin for uncertainty. The descriptors under the graph are descriptive enough to make sure people understand what is happening and why the graph has these lines.

I do support showing inaccurate data, but I don't see any inaccurate or underestimations as stated in the issue.. I see predictions and unreliable data, which is vastly different.

The need to show unreliable data is debatable, I think that you can show it with a good descriptor, which seems like it is the case.

Asking the RIVM to improve their predictions and confidence interval is way out of scope of an Github issue.

**Comment by VWSCoronaDashboard7** [comment] 2020-09-30 12:16
@EwoutH As explained in https://github.com/minvws/nl-covid19-data-dashboard/issues/410, the 95% CI means not all predications will be accurate. With a rapid rise in the number of confirmed cases, as we've seen recently, it may well be that a predication falls in that other 5% category. Singling out specific cases where the prediction was out of bounds and applying this to a general conclusion that the information would be "misleading" or "inaccurate" is a perceptual bias. To make a call on the usefulness of this number you'd need to look at a larger timeframe, conclude when and when it was not within bounds and look at other factors such as how it effected policy- or decisions making. 

We take all feedback seriously and as stated in the previous issue will take your point(s) under advisement for further design revisions to this indicator. There likely won't be an even more accurate prediction model. Our strategy in this is explaining the uncertainty as best we can. Nobody can predict the future with utmost certainly, especially with a virus that spreads at an exponential pace. This information is the best we have at the given point in time.

On your suggestion of upstreaming your concerns, feel free to contact the RIVM directly via https://www.rivm.nl/contact/vragenformulier for example. This is, as @galavanto mentions, outside of the scope of this repository.

**Closed by VWSCoronaDashboard7** 2020-09-30 12:16 UTC

**Comment by EwoutH** [comment] 2020-10-13 15:41
> As explained in #410, the 95% CI means not all predications will be accurate. With a rapid rise in the number of confirmed cases, as we've seen recently, it may well be that a predication falls in that other 5% category. Singling out specific cases where the prediction was out of bounds and applying this to a general conclusion that the information would be "misleading" or "inaccurate" is a perceptual bias. To make a call on the usefulness of this number you'd need to look at a larger timeframe, conclude when and when it was not within bounds and look at other factors such as how it effected policy- or decisions making.

@VWSCoronaDashboard7 This statement it most certainly right. I should have backed my issue with more data. I found this issue on a hunch, playing a bit with the graphs and the data. Now I got some time (and hystorical data thanks to the Wayback Machine!) to proper investigate it: 
![Screenshot_539](https://user-images.githubusercontent.com/15776622/95881968-6d3f4900-0d79-11eb-81ed-d57643ca79a0.png)
As can been seen, every single week the new prediction confidence interval drops significantly. A week later the calculated R's don't display this drop, or at least not so significantly.

The R of the 20 days that can be compared directly, only 3 fit in the confidence interval of last weeks prediction.

Here's the Excel-file I used to compare the data and create the graph: [RIVM-R-20201013.xlsx](https://github.com/minvws/nl-covid19-data-dashboard/files/5372439/RIVM-R-20201013.xlsx)
