### ISSUE TITLE
data file for sewage measurements not yet updated

### ISSUE THREAD

**Issue by jeroenbreen** [minvws/nl-covid19-data-dashboard#255] opened 2020-09-08 15:49 UTC
### Describe the bug, issue or concern

The data file for sewage measurements is not yet updated (https://data.rivm.nl/covid-19/COVID-19_rioolwaterdata.json), while the Corona Dashboard does have some updated data concerning the sewage measurements.

**Comment by VWSCoronaDashboard7** [comment] 2020-09-08 17:46
Thanks for taking the time to notify us of this issue. We noticed the open data file not being updated as well during our data load so we contacted the RIVM and have asked to send the file directly to us. Through a manual load of that file the dashboard has been updated with new sewage measurements. 

RIVM is looking into the cause of the open data file not updating on their data portal. As that portal is not related to this repo, closing this issue.

**Closed by VWSCoronaDashboard7** 2020-09-08 17:46 UTC
